//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCentreFormation_Metier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formateur()
        {
            this.SessionFormation = new HashSet<SessionFormation>();
            this.Formation = new HashSet<Formation>();
        }
    
        public int Identifiant { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string NomFichierPhoto { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public bool IntervenantExterieur { get; set; }
        public string Infos { get; set; }
        public int IdCivilite { get; set; }
    
        public virtual Civilite Civilite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionFormation> SessionFormation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formation> Formation { get; set; }
    }
}
