//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCentreFormation_Metier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiaire2SessionFormation
    {
        public int IdSessionFormation { get; set; }
        public int IdStagiaire { get; set; }
    
        public virtual Stagiaire Stagiaire { get; set; }
    }
}
