//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCentreFormation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formation()
        {
            this.DemandeClient = new HashSet<DemandeClient>();
            this.SessionFormation = new HashSet<SessionFormation>();
            this.Formateur = new HashSet<Formateur>();
        }
    
        public int Identifiant { get; set; }
        public string Reference { get; set; }
        public string Libelle { get; set; }
        public short NombreJours { get; set; }
        public short Prix { get; set; }
        public string Description { get; set; }
        public int IdTheme { get; set; }
        public Nullable<int> Type { get; set; }
        public string Url { get; set; }
        public string Lieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeClient> DemandeClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionFormation> SessionFormation { get; set; }
        public virtual Theme Theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formateur> Formateur { get; set; }
    }
}
