//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCentreFormation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormationEntities : DbContext
    {
        public FormationEntities()
            : base("name=FormationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Civilite> Civilite { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commercial> Commercial { get; set; }
        public virtual DbSet<DemandeClient> DemandeClient { get; set; }
        public virtual DbSet<Formateur> Formateur { get; set; }
        public virtual DbSet<Formation> Formation { get; set; }
        public virtual DbSet<SecteurActivite> SecteurActivite { get; set; }
        public virtual DbSet<SessionFormation> SessionFormation { get; set; }
        public virtual DbSet<Stagiaire> Stagiaire { get; set; }
        public virtual DbSet<Stagiaire2SessionFormation> Stagiaire2SessionFormation { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
    }
}
