//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCentreFormation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionFormation
    {
        public int Identifiant { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public bool Inter { get; set; }
        public int IdFormateur { get; set; }
        public int IdCommercial { get; set; }
        public int IdFormation { get; set; }
    
        public virtual Commercial Commercial { get; set; }
        public virtual Formateur Formateur { get; set; }
        public virtual Formation Formation { get; set; }
    }
}
